DATANAME = 'METR-LA'
TIMESTEP_IN = 12
TIMESTEP_OUT = 3
N_NODE = 207
CHANNEL = 1
BATCHSIZE = 64
LEARN = 0.001
EPOCH = 500
PATIENCE = 30
OPTIMIZER = 'Adam'
# OPTIMIZER = 'RMSprop'
# LOSS = 'MSE'
LOSS = 'MAE'
TRAINRATIO = 0.8 # TRAIN + VAL
TRAINVALSPLIT = 0.125 # val_ratio = 0.8 * 0.125 = 0.1
FLOWPATH = 'data/METRLA/metr-la.h5'
ADJPATH = 'data/METRLA/W_metrla.csv'

